### DISCUSSION TITLE
dynamic completion

### DISCUSSION THREAD

**Discussion by easyrider14** [bashly-framework/bashly#181] [Q&A] [answered]
Hi

I'm playing with the bash completion part of bashly, and try to add some dynamic behavior

I'm trying to add a command whose parameter is dynamically retrieve through a REST api request

my completion is defined as follow :

```
- name: delete
  help: delete an object instance
  group: delete
  commands:
  - name: processor
    help: delete a processor instance
    completions:
     - $(TOKEN=$(cat /tmp/access_token.txt) && eval $(cat /etc/env/environment.txt | grep API_URL) && curl -sL --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Bearer ${TOKEN}" ${API_URL}/processors/ | jq .[].name)
```

but the validation fails at column 169 (colon after Accept)

if I remove this part and it manually in the generated completion script, everything work fine
it may be better to add a function but I can't figure how. It does not seem possible to add a sort of initialize script for the completion part.

thanks

**Comment by DannyBen** [comment, marked as answer]
Interesting.

Well, this seems like a gross abuse of the completions mechanism, but I believe it should be still possible.
It is hard for me to help you debug this problem since I have no access to your completions "server".

That said, the error you are getting is not from bashly itself, but from the YAML parser.
The below syntax should make it pass validation (the only thing you care about is the pipe in the completions string):

```yaml
name: delete
help: Delete an object instance

commands:
- name: processor
  help: delete a processor instance
  completions: # this is the secret
  - |
    $(TOKEN=$(cat /tmp/access_token.txt) && eval $(cat /etc/env/environment.txt | grep API_URL) && curl -sL --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Bearer ${TOKEN}" ${API_URL}/processors/ | jq .[].name)
```

But still - this would not work.
Your completion command **must not include quotes** since it will be placed into a quoted place already. You may be able to get away with escaped quotes, but I am not sure.

I would consider this approach instead:

1. In your bashly script, make a command that intends to get these completions, for example: `yourcli get-completions`
2. Optionally, if you don't want your users to see this command, [mark it as `private`](https://bashly.dannyb.co/configuration/command/#private)
3. Then, in your completion list, just add it as a simple command, like so:

```yaml
- name: processor
  help: delete a processor instance
  completions:
    - $(mycli get-completions)
```

Now, you can test your completion command in isolation, and if it returns a compatible completions string (whitespace dlimted string), then there is no reason it wont work in the completions itself.

### Full working example:

```yaml
# bashly.yml
name: cli

commands:
- name: test
  help: Test the completions
  completions:
    - $(./cli get-completions)
- name: get-completions
  help: Return some completions
  private: true
```

```bash
# src/get_completions_command.sh
echo "one two three"
```

Then you run:

```bash
$ bashly g
$ bashly add comp script
$ source completions.bash

# test completions
$ ./cli get-completions
one two three

$ ./cli test <tab>
# and you get one two three here as well
```
