### DISCUSSION TITLE
Adding "args" Before Command

### DISCUSSION THREAD

**Discussion by rience** [bashly-framework/bashly#292] [Q&A]
Hi,

I'm trying to write script to help managing Kubernetes pods. These pods have metadata like `app` or `branch`. An idea is that I'd have bash script that will take name of an `app` and then name of `branch` and then run passed command in pod. Something like this

```
./kube app-name branch-name ls
```

So I tried to do it this way
```
args:
  - name: app
  - name: branch

commands:
  - name: command
```

However, Bashly does not allow to use `args` at root level and `commands` in the same time. I can do it this way

```
./kube ls app-name branch-name
```

But for usability - it'd be great to have name of command at the end, since that's something that people would change very often. Thank you in advance for any ideas.

**Comment by DannyBen** [comment]
What other CLI that you know has this kind of syntax?

**Reply by rience** [reply]
Fair point. I can't think of anything. It just feels right for me that in this case user selects pod first (with `app` and `branch`) and then executes command. Just looking for some ideas whether this can be done.

**Reply by DannyBen** [reply]
Hmm. I would need to think about it, but I don't think there is currently a way.
Just to be sure - confirm you want this pattern to work

```
kube APP BRANCH COMMAND [options]
```

All mandatory? Or some optional, like this?

```
kube APP [BRANCH] COMMAND [options]
```

We recently added support for global flags (flags before the command) in #271 - I wonder if same can be done for args without complicating things.

**Reply by rience** [reply]
At the moment - both arguments would be mandatory.

**Reply by DannyBen** [reply]
Well, at the moment, I do not believe it is possible, but perhaps similar to the work done in #271, it *could* be implmeneted.
I am not yet sure that it *should* though.
Let me sleep on it.

**Reply by rience** [reply]
That's what I was trying to do - have global `flags` and then `commands`. But at the moment I couldn't figure out how to have more than one global flag

```
name: kube
help: Helps with managing containers deployed with Kubernetes
version: 0.1.0

flags:
  - long: --app
    short: -a
    arg: app
    allowed: ['xxx', 'yyy']
    required: true
    help: Name of application.
  - long: --branch
    short: -b
    arg: branch
    required: true
    help: Name of branch

commands:
  - name: ls
```

After I generate script it either allows me to specify `-a` or `-b`. Not both.

```
./kube -a xxx -b master ls
invalid option: -b
```

**Reply by DannyBen** [reply]
This seems to be a bug. I will open one.
#293

**Reply by DannyBen** [reply]
Ok - that is an embarrassing bug.... thanks for catching it.

However, this does not fix your issue - having it with flags, while complying with your "order intuition", is less nice than just having the app and branch as args. I will first fix the bug, and then see if having args do the same is something worth pursuing.

**Reply by rience** [reply]
Come on! Bugs happen :) Thank you for fixing that so quickly.

It's not fixing the issue 100% but majority is there. What users probably will do is this

1. Reverse searching in bash to get last `./kube` execution
2. Hit backspace multiple times and type in their command

Which is basically what I wanted to have - command at the end.

**Reply by DannyBen** [reply]
I will complete the specs tomorrow, then you will be able to use the [edge](https://github.com/DannyBen/bashly/tree/master/edge#testing-unreleased-edge-bashly-versions) version if you wish.

It will take me another day or two to consider the global args and release a version.

**Reply by DannyBen** [reply]
I have merged the fix to allow multiple global flags, and pushed a docker `edge` version.
If you wish to try the new version prior to a version bump, [you can](https://github.com/DannyBen/bashly/tree/master/edge#readme).

Otherwise, I will probably release towards the end of the week, unless it is urgent for you.

**Reply by rience** [reply]
Thank you. It works great :)

There is one more thing though - completion for global flags works globally for all flags. Sorry :(

**Reply by DannyBen** [reply]
> There is one more thing though - completion for global flags works globally for all flags. Sorry :(

Hmm... I will need to check this. Not sure I can fix it.
And nothing to be sorry about, on the contrary - appreciate the report.

**Reply by DannyBen** [reply]
Okay @rience - it seems you have opened a can of worms... (thank you for that).

This discussion has helped in uncovering several bugs:

- https://github.com/DannyBen/completely/issues/37
- https://github.com/DannyBen/completely/issues/38
- https://github.com/DannyBen/bashly/issues/296

I am not 100% that fixing them will solve your issue, but right now completions for CLIs with global flags is completely broken.

I will need to fix these first, and then we can see where we stand.

**Reply by DannyBen** [reply]
So - I *hope* I got all the quirks out of the system.

The fixed bashly (together with completely 0.5.1) is on the master branch and the edge docker.

My test case that matches your scenario (as I understand) is this:

```yaml
# bashly.yml
name: cli

flags:
- long: --app
  arg: app
  allowed: [app1, app2]
  required: true

- long: --branch
  arg: branch
  default: master

commands:
- name: ls

  flags:
  - long: --all
  - long: --compact
```

Then, you can run this shell script below to test the different completion cases:

```bash
#!/usr/bin/env bash
bashly add comp yaml completely.yaml --force

run() {
  echo "$ $@<tab>"
  completely test "$@"
  echo
}

run "cli "
run "cli --"
run "cli --app "
run "cli --app app1 ls --"
```

The output:

```
$ cli <tab>
ls

$ cli --<tab>
--app
--branch
--help
--version

$ cli --app <tab>
app1
app2

$ cli --app app1 ls --<tab>
--all
--compact
--help
```

You can also notice that the generated `completely.yaml` now contains a wildcard (`*`) wherever the completion is allowed to have other words.

```yaml
# completely.yaml
---
cli:
- "--app"
- "--branch"
- "--help"
- "--version"
- "-h"
- "-v"
- ls
cli*--app:
- app1
- app2
cli*ls*:
- "--all"
- "--compact"
- "--help"
- "-h"
```
