### DISCUSSION TITLE
Is it possible to have a default subcommand of a subcommand?

### DISCUSSION THREAD

**Discussion by halostatue** [bashly-framework/bashly#325] [Q&A] [answered]
I’m working on a command that looks something like this:

```
usage: cli subcommand [options] [arguments...]

Subcommands:
  cli list [installed]
  cli list releases
  cli list branches
```

That is, if `cli list` is run, rather than showing help, it should run `cli list installed`. Ideally, it should pass supported flags on to `cli list installed`.

**Comment by DannyBen** [comment, marked as answer]
Sure. In general, everything in the documentation about [Command](https://bashly.dannyb.co/configuration/command/), refers to command or subcommand (at any nesting level). The [default](https://bashly.dannyb.co/configuration/command/#default) directive is what we need.

Here is an example:

```yaml
# bashly.yml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: list
  alias: l
  help: Show all sorts of lists

  commands:
  - name: installed
    help: Show installed
    default: force

  - name: releases
    help: Show releases
  
  - name: branches
    help: Show branches
```

which generates:

```shell
$ ./cli list
# this file is located in 'src/list_installed_command.sh'
# code for 'cli list installed' goes here
# you can edit it freely and regenerate (it will not be overwritten)
args: none
```

```shell
$ ./cli -h
cli - Sample application

Usage:
  cli COMMAND
  cli [COMMAND] --help | -h
  cli --version | -v

Commands:
  list   Show all sorts of lists

Options:
  --help, -h
    Show this help

  --version, -v
    Show version number
```

```shell
$ ./cli list -h
cli list - Show all sorts of lists

Alias: l

Usage:
  cli list COMMAND
  cli list [COMMAND] --help | -h

Commands:
  installed   Show installed (default)
  releases    Show releases
  branches    Show branches

Options:
  --help, -h
    Show this help
```
