### DISCUSSION TITLE
Dynamic completion with argument

### DISCUSSION THREAD

**Discussion by vdesabou** [bashly-framework/bashly#376] [General]
Hello ! 

I've followed recommendations from https://github.com/DannyBen/bashly/discussions/181 where I have setup a private command:

```yml
- name: get-examples-list-with-fzf
  help: Return some completion for examples list
  private: true
  args:
  - name: file
    required: false
    help: current
```

Script `get_examples_list_with_fzf_command.sh`:

```sh
file="${args[file]}"
get_examples_list_with_fzf "$file"
```

where function is doing:

```sh
find $dir2 -name \*.sh  | fzf --query "$1" --delimiter / --with-nth '-3,-2,-1' --preview 'cat {}'
```

Which I call like this:

```yml
  flags:
  - long: --file
    short: -f
    required: true
    validate: file_exists
    arg: file
    completions:
      - $(playground get-examples-list-with-fzf "$cur")
    help: |-
      Example file to run.
```

My private command works fine, i.e when I call it, it find the right file using `find` and `fzf` and using the argument as query

```bash
playground get-examples-list-with-fzf "test jdbc"
```

![CleanShot 2023-04-12 at 13 58 47](https://user-images.githubusercontent.com/4061923/231450853-c968c71e-444b-41a6-86fb-86537eb96bdf.gif)

Now If I run it with my real command:

```
playground run -f jdbc
```

It will show the fzf selection 3 times and in the end it does not select the file I want, see:

![CleanShot 2023-04-12 at 14 03 22](https://user-images.githubusercontent.com/4061923/231451631-eeae4049-d0a0-4daa-b755-19e5d06139da.gif)

Any idea why ?

In my completion bash, it generates:

```bash
    'run'*'-f')
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_playground_completions_filter "$(playground get-examples-list-with-fzf "$cur")")" -- "$cur" )
      ;;
```

**Comment by DannyBen** [comment]
I am not sure. There are too many variables in play here, most of which are outside the scope of what bashly and completely were designed to do.

I think you should simplify. Why not remove the private completions command and simply do something like this:

```yaml
name: cli
help: Sample application

commands:
- name: run
  flags:
  - long: --file
    short: -f
    required: true
    arg: file
    completions:
      - $(fzf --query "$cur")
    help: |-
      Example file to run.
```

Also, you can use completely itself to easily test different commands.
You can convert your bashly yaml to completely.yaml by running `bashly add completions_yaml` and then renaming the file to `completely.yaml`.

See this completely.yaml as an example:

```yaml
---
cli:
- run
cli run:
- "--file"
- "-f"
cli run*--file: &1
- $(fzf --query "$cur")
cli run*-f: *1
```

then you can test commands with 

```bash
$ completely test "cli run -f "   # note the trailing space
$ completely test "cli run -f src"
```

Note that these commands run directly on the completely.yaml file, without the need to regenerate anything.
