### DISCUSSION TITLE
different completion lists for required arguments

### DISCUSSION THREAD

**Discussion by unimock** [bashly-framework/bashly#447] [Q&A]
Hello DannyBen

First of all, thank you for this cool tool! Unfortunately I only stumbled upon it now.

I want to realize a script with multiple required arguments of different types and so different completion lists for each argument.

```
./cli host assign <host> <vserver>
```

In my naive approach I tried following:

```
- name: host
  help: assign existing host to an virtual server
  commands:
  - name: assign
    args:
    - name: host
      help: Hostname
      required: true
      completion:
        - $(get_availible_hosts)
    - name: vserver
      help: Virtual server
      required: true
      completion:
        - $(get_availible_vserver)
```
but using "completions" in "args" ist not supported from bashly.
Also using "allowed:" is not a option, because it mixed up both lists.

I am aware that this can be achieved with flags, like ```./cli host assign --vserver <vserver> <host>```

But this notation doesn't fit into my existing environment.

Is there a configuration way to get this behavior?

Thanks and best regards

Michael
