### DISCUSSION TITLE
Generic flag available for all commands ?

### DISCUSSION THREAD

**Discussion by vdesabou** [bashly-framework/bashly#491] [Ideas]
I often find myself needing to set `set -x` in generated script to troubleshoot issues.

I was thinking to add a generic flag like `-vvv` that would apply to all my commands.

Do you see a way to do that without having to declare the flag in each command ?

Thanks

**Comment by DannyBen** [comment]
There is more than one way to achieve what you want.

If this is intended for developer-side debugging, I would avoid adding it as a user flag, and instead add something like this:

```bash
# src/initialize.sh
[[ $DEBUG ]] && set -x
```

*(See [Function Hooks](https://bashly.dannyb.co/advanced/hooks/))*

then you can set the `DEBUG` environment variable to set a different behavior at runtime of your script.

If you wish to still have a globally available flag, you can simply [add it on the parent command](https://bashly.dannyb.co/configuration/command/#flags) (see note on this page).

For example:

```yaml
# src/bashly.yml
name: cli
help: Sample application
version: 0.1.0

flags:
- long: --verbose
  short: -v
  repeatable: true
  help: Set verbose output

commands:
- name: download
  alias: d
  help: Download a file

  flags:
  - long: --force
    short: -f
    help: Overwrite existing files

- name: upload
  alias: u
  help: Upload a file
```

```bash
$ ./cli -vvv download -f
# this file is located in 'src/download_command.sh'
# code for 'cli download' goes here
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[--force]} = 1
- ${args[--verbose]} = 3
```

Does this help?
