### DISCUSSION TITLE
Is there a way to invoke a command from another command?

### DISCUSSION THREAD

**Discussion by dragonfleas** [bashly-framework/bashly#522] [Q&A] [answered]
Let's say you have a two high level functions in `/src/create_command.sh` & `/src/upgrade_command.sh`

and your bashly config look like

```
name: component
help: Manages the creation and upgrading of components
version: 0.1.0

commands:
- name: create
  help: Creates a component for use
  
  flags:
  - long: --name
    short: -n
    arg: component_name
    default: my_component 
    
- name: upgrade
  help: Upgrades a component to the latest version
  
  flags:
  - long: --name
    short: -n
    arg: component_name
    default: myComponent 
  - long: --version
    short: -v
    arg: component_version
    required: true
```

Let's say `./component upgrade` wants to invoke the `create_component` function and run some additional logic, is there a way to access one command from another within the bashly abstraction? Or is the best way to solve this problem to decompose even high level functions into `/src/lib` and have the main commands simply just be a function wrapper/argument consumer like

```
#!/usr/bin/env bash
# create_command.sh
# uses /src/lib/create_component.sh

inspect_args

component_name=${args[--name]}

create_component "$component_name"
```

And invoke that same create_component function in `/src/lib/create_component.sh` from `/src/upgrade_component.sh`?

It would be really cool for to be able to just invoke itself with another command like

```
#!/usr/bin/env bash
# upgrade_command.sh
# uses component create

inspect_args

component_name=${args[--name]}
component_version=${args[--version]}

...old component teardown logic...

component create --name "$component_name" --version "$component_version"
```
