### DISCUSSION TITLE
pls - Project Level Shortcuts uses bashly

### DISCUSSION THREAD

**Discussion by codevogel** [bashly-framework/bashly#542] [Show and tell]
Hi, I built a nice little CLI tool using bashly:

Project Level Shortcuts (pls) is a command-line tool designed to streamline your workflow by allowing you to create, manage, and execute custom aliases for frequently used commands.

It manages your aliases in `yml` files, so you can be sure they don't interfere with other commands. Aliases can also be added on a local project-based scope, where they overwriting duplicate system-wide aliases.

This makes it easy to run, for example, multiple testing frameworks across different projects by just typing `pls test`.  

Check it out here: https://github.com/codevogel/pls

**Comment by DannyBen** [comment]
Wow - this looks super cool, and seems like it took quite a lot of effort. Just the README seems like a couple of days of work.

I am going to check it out for sure - I love aliasing commands, have built a few aliasing helpers myself.

Can I list it on https://bashly.dannyb.co/examples/#real-world-examples

Also I am curious if you had any issues or annoyances with bashly during the development, or anything that would have made the development process easier.

**Reply by codevogel** [reply]
Oh - I was creating some issues for `pls` and saw that I forgot to reply to this message.

You are more than welcome to list it in the real world examples. In fact, I think it'd be cool!

Regarding issues I had developing with bashly, I think I already pointed them out in the earlier question discussions I created. 

The docs  do feel a little overwhelming at times, hence why I missed some features that you then kindly suggested I should take a look at. But -  I think that's mainly due to the nature that bashly just offers you _a lot_ of options. The docs themselves are great: everything you need is in there, there's clear examples, and yet it doesn't feel too cluttered and you can easily find your way to what you want.
I guess the harder part is knowing _what_ to look for.

Maybe a way to improve this could be to add a couple of tutorial/sample projects, in which you can write a simple CLI tool from start to finish (e.g. a tool that adds numbers from one file to numbers from another file) - including adding some simple code (the examples mostly contain bashly .yml examples and the output of those commands - I don't mean 'write a bash scripting tutorial', but just show how you could implement a feat, making use of the arguments/env vars etc.). You could start pretty bare-bones (just run and it adds the numbers of file `a` and `b`), then slowly work up to adding arguments (specify path for `a` and `b`, flags (`--subtract` instead), etc.

Though to be fair, I'd consider the work/reward ratio there, because as I said, the docs are already very clear. With a little more patience I would've found my way around.

**Reply by DannyBen** [reply]
> list it in the real world examples

I was optimistic and [already did](https://bashly.dannyb.co/examples/#real-world-examples).

As for the tutorials / example projects, thanks for the feedback. I thought that having an extensive index of examples, each being minimal to only a single topic would serve as a "choose your path" tutorial.

You are right in identifying the fact that the examples are mostly about the bashly configuration itself and less about the needed bash code - however this was one of bashly's goals; to not force you to learn anything in bash itself - you just get that `$args` dictionary and that is it. The rest is up to you. If this particular message is not conveyed clearly, then we need to improve the docs.

Perhaps the [Getting Started](https://bashly.dannyb.co/usage/getting-started/) page could get some love.

**Comment by DannyBen** [comment]
So I have tested this a little deeper, using the very useful docker environment.

### What I like

- Love the name. I am sure it is not a coincidence that it is also a shortcut to "please", so typing "pls deploy" makes it fun to use.
- Love the detailed README and --help - makes it very easy to grasp what it does and how it does it, quickly.
- Love the "first run" confirmation - makes it feel safe to run.
- Love the fzf menu.
- Love the cascading nature of the `.pls.yml` files.
- Love the thorough test/spec suit.

### Some personal observations

- I am usually not a huge fan of commands that have underscores in them. I am guessing this naming convention was picked to distinguish these commands from user aliases.
- I wonder if to mitigate the above, it is worth considering having all of the "internal" commands be converted to flags instead: `pls -l`, `pls -p` etc. This frees the "command namespace" completely for the user aliases.
- I wonder - especially since fzf is a dependency - if it would be possible to allow the user to type just the first few letters of an alias, and if they resolve to a single command, run this command: `pls dup` => `pls duplicate`.
- There is a hefty number of environment variables. I wonder if it would make sense to use a configuration file (`~/.plsrc`) for configuring all at once. Then, there could be only one environment variable pointing to the path of the configuration file.
- I see that when you have an option (like `--destination`) that requires the value to be one of a whitelist, you are not using [flag.allowed](https://bashly.dannyb.co/configuration/flag/#allowed)` and instead do a custom validation.

**Reply by codevogel** [reply]
Thanks for the remarks!

I chose the commands with underscores as I want it running `pls` to feel as short as possible. Hence I gave each command a short one-letter alias, and picked long names that realistically few people would use for an alias themselves (I expect people to `pls test`, not `pls e test` or `pls execute_alias test`, and `pls l` instead of `pls list_aliases`).
What kind of annoys me about that approach is that someone might realistically want to use `a` (`b`..`c`..) as an alias, and right now the shortest would be to resort to `pls e a`, as `pls a` is the shorthand for `add`. 
I have been considering whether it that might be better with an all-flags approach, but I was unsure whether `pls` or `pls test` could then still default to `pls -e` or `pls -e -a test` respectively?

I think I might add auto-completion of aliases to the roadmap for the same reason: I want users to type as little as possible.

You're probably right in moving the config to `~/.plsrc`: I don't like the huge list in the --help command, especially as they are supposed to be for superusers, and shouldn't be messed too much for normal usage. 

I totally glossed over `flag.allowed` so I'll look into that too!

**Reply by DannyBen** [reply]
Here is baseline for converting the commands to options.
The one thing that you will need to do is to verify that when `--add ALIAS` is invoked, the command line also includes `--command`

I wonder if there is anything that can be done in bashly for it - like a `needs: [--command]` option or something of that sort (similar to `conflicts`).

Note that I did not do an `executa_alias` command - since the one and only positional argument means we are required to execute this alias.

```yaml
name: pls
help: Project Level Shortcuts

args:
- name: alias
  help: Alias to run

flags:
- long: --pick
  short: -p
  help: Interactively pick an alias to run

- long: --add
  short: -a
  arg: alias
  help: Add an alias.

- long: --remove
  short: -r
  arg: alias
  help: Remove an alias.

- long: --clear
  short: -C
  help: Clear cache.

- long: --command
  short: -c
  arg: command
  help: The command to associate with the alias (use in conjunction with --add or --remove).

- long: --force
  short: -f
  help: Overwrite the alias if it already exists (use in conjunction with --add).

- long: --destination
  short: -d
  arg: destination
  allowed: [g, l, h, global, local, here]
  help: Specify the destination for --add and --remove.

examples:
  - "pls deploy                  # run an alias"
  - "pls -p                      # pick an alias from a menu"
  - "pls -a alias -c command -f  # add an alias forcfully"
  - "pls -r alias -d l           # remove an alias from local"
  - "pls -C                      # clear cache"
```
