### DISCUSSION TITLE
Why can't I use validations on environment_variables in bashly.yml

### DISCUSSION THREAD

**Discussion by ichoosetoaccept** [bashly-framework/bashly#545] [Q&A] [answered]
Bashly [supports validations](https://bashly.dannyb.co/advanced/validations/#custom-validations) for arguments and flag arguments but not for environment variables. Why?
For example, this is throwing errors on bashly generate:
```
environment_variables:
  - name: RELEASES_FOLDER
    help: Path to the releases folder
    default: /export/home/releases
    validate: dir_exists
  - name: LOG_DIR
    help: Directory for storing log files
    default: ${RELEASES_FOLDER}/logs
    validate: dir_exists
```

This would save me from having to write my own "folder exists" validation function.. unless I'm missing something?

Thanks for reading!
