### DISCUSSION TITLE
Add a way to conditionally hide individual commands from the command list

### DISCUSSION THREAD

**Discussion by meleu** [bashly-framework/bashly#624] [Ideas]
I'm aware about the `private` option (from the [command-private](https://github.com/DannyBen/bashly/tree/master/examples/command-private#readme) and [private-reveal](https://github.com/DannyBen/bashly/tree/master/examples/private-reveal#readme)), but I think they don't provide the solution for my usecase.

> I'm going to suggest a new feature below, but if there's a way to achieve such result with current implementation, please just show me how to achieve that.

My intention is to show some subcommands on the help based on which directory I'm in (actually I wanna use the git URL, but using the directory here for simplicity sake).

Hypothetical example:

- if I call the script from `~/src/frontend` directory, I want to expose the `vite-server` option.
- if I call from `~/src/backend` dir, I want to expose the `dbmigrate` option (and hide the `vite-server`)
- if I call from any other directory, hide both `vite-server` and `dbmigrate`

I envisage the usage to be like this:

```yaml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: generic
  help: Generic subcommand (always available)

- name: vite-server
  help: Starts only the vite-server
  # show this command in help only if filter_is_frontend returns success
  private_filter: is_frontend

- name: dbmigrate
  help: Run database migration
  # show this command in help only if filter_is_backend returns success
  private_filter: is_backend
```

Maybe the rules for `private_filter` could be the same as the ones for `filter`.
